<a href="https://colab.research.google.com/github/lOmarMisbahl/MAGIC-GAMMA-TELESCOPE-MACHINE-LEARNING/blob/main/MAGIC_GAMMA_TELESCOPE_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data = np.loadtxt('magic04.data', delimiter=',', usecols=[0,1,2,3,4,5,6,7,8,9])
labels = np.loadtxt('magic04.data', delimiter=',',dtype=np.str, usecols=[10])

In [ ]:
rem = 5644
i=0
while rem>0 :
    temp = len(labels)-1
    print(temp)
    while temp>=0 :
        if labels[i]=='g' :
            if randint(0, 1)==0 :
                continue
            labels =np.delete(labels,i)
            data =np.delete(data,i,0)
            if len(data)!=len(labels):
                print("error")
                break
            i-=1
            rem-=1
            temp-=1
            if rem <1 :
                break
        i+=1
print(len(labels))

19019
13376


In [ ]:
l = 0
r =0 
for i in range(len(labels)) :
    if labels[i]=='g':
        l+=1
    else :
        r+=1
print(l)
print(r)

6688
6688


In [ ]:
temp = int(len(labels)*0.7)
train_data = data[:temp]
train_label = labels[:temp]
test_data = data[temp:]
test_label =labels[temp:]
print(len(train_label))    

9363


In [ ]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(train_data, train_label)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
from sklearn.metrics import *
wrong = 0 
pred = []
for i in range(len(test_label)):
    pred.append(clf.predict(test_data[i].reshape(1, -1)))  
    if pred[i]!=test_label[i] :
        wrong+=1 ;
print(wrong)
print(accuracy_score(test_label, pred))
print(precision_score(test_label, pred,labels=['h','g'],pos_label='h'))
print(recall_score(test_label, pred,labels=['h','g'],pos_label='h'))
print(f1_score(test_label, pred,average=None))
print(confusion_matrix(test_label, pred))

1061
0.7356092698729131
0.6769911504424779
0.44315713251267197
[0.81518899 0.5356674 ]
[[2340  292]
 [ 769  612]]


In [ ]:

from sklearn.neighbors  import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=10)
neigh.fit(train_data,train_label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [ ]:
from sklearn.metrics import *
wrong = 0 
pred = []
for i in range(len(test_label)):
    pred.append(neigh.predict(test_data[i].reshape(1, -1)))
    if pred[i]!=test_label[i] :
        wrong+=1 ;
print(wrong)
print(accuracy_score(test_label, pred))
print(precision_score(test_label, pred,labels=['h','g'],pos_label='h'))
print(recall_score(test_label, pred,labels=['h','g'],pos_label='h'))
print(f1_score(test_label, pred,average=None))
print(confusion_matrix(test_label, pred))

844
0.7896835285322701
0.7378210806023029
0.6031860970311369
[0.84699057 0.66374502]
[[2336  296]
 [ 548  833]]


In [ ]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(train_label)
regr = AdaBoostRegressor(random_state=0, n_estimators=100)
regr.fit(train_data,le.transform(train_label))

AdaBoostRegressor(base_estimator=None, learning_rate=1.0, loss='linear',
                  n_estimators=10000000, random_state=0)

In [ ]:
from sklearn.metrics import *
wrong = 0 
pred = []
for i in range(len(test_label)):
    x=round(regr.predict(test_data[i].reshape(1, -1))[0])
    pred.append(le.inverse_transform([x])[0])
    if pred[i]!=test_label[i] :
        wrong+=1
print(wrong)
print(accuracy_score(test_label, pred))
print(precision_score(test_label, pred,labels=['h','g'],pos_label='h'))
print(recall_score(test_label, pred,labels=['h','g'],pos_label='h'))
print(f1_score(test_label, pred,average=None))
print(confusion_matrix(test_label, pred))

764
0.8096187390979317
0.7382239382239382
0.6922519913106444
[0.85719626 0.71449925]
[[2293  339]
 [ 425  956]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(train_label)
clf = RandomForestClassifier(max_depth=3, random_state=0,n_estimators=100)
clf.fit(train_data,le.transform(train_label))

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
from sklearn.metrics import *
wrong = 0 
pred = []
for i in range(len(test_label)):
    x=round(clf.predict(test_data[i].reshape(1, -1))[0])
    pred.append(le.inverse_transform([x]))
    if pred[i]!=test_label[i] :
        wrong+=1
print(wrong)
print(accuracy_score(test_label, pred))
print(precision_score(test_label, pred,labels=['h','g'],pos_label='h'))
print(recall_score(test_label, pred,labels=['h','g'],pos_label='h'))
print(f1_score(test_label, pred,average=None))
print(confusion_matrix(test_label, pred))

1103
0.7251432843259407
0.5688800792864221
0.8312816799420709
[0.7616166  0.67549279]
[[1762  870]
 [ 233 1148]]


In [ ]:
from sklearn import tree
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(train_label)
clf = tree.DecisionTreeClassifier()
clf.fit(train_data,le.transform(train_label))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
from sklearn.metrics import accuracy_score
wrong = 0
pred = []
for i in range(len(test_label)):
    x=round(clf.predict(test_data[i].reshape(1, -1))[0])
    pred.append(le.inverse_transform([x]))
    if pred[i]!=test_label[i] :
        wrong+=1
print(wrong)
print(accuracy_score(test_label, pred))
print(precision_score(test_label, pred,labels=['h','g'],pos_label='h'))
print(recall_score(test_label, pred,labels=['h','g'],pos_label='h'))
print(f1_score(test_label, pred,average=None))
print(confusion_matrix(test_label, pred))

898
0.7762272614004485
0.639193083573487
0.8030412744388125
[0.81710794 0.71181001]
[[2006  626]
 [ 272 1109]]


In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense
model = Sequential()
model.add(Dense(12, input_dim=10, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(train_label)
model.fit(train_data,le.transform(train_label), epochs=20, batch_size=10)

Epoch 1/20
937/937 [==============================] - 2s 1ms/step - loss: 1.8624 - accuracy: 0.5312
Epoch 2/20
937/937 [==============================] - 1s 1ms/step - loss: 0.6516 - accuracy: 0.5665
Epoch 3/20
937/937 [==============================] - 1s 1ms/step - loss: 0.5637 - accuracy: 0.7007
Epoch 4/20
937/937 [==============================] - 1s 1ms/step - loss: 0.5289 - accuracy: 0.7438
Epoch 5/20
937/937 [==============================] - 1s 1ms/step - loss: 0.4952 - accuracy: 0.7612
Epoch 6/20
937/937 [==============================] - 1s 1ms/step - loss: 0.4784 - accuracy: 0.7722
Epoch 7/20
937/937 [==============================] - 1s 1ms/step - loss: 0.4710 - accuracy: 0.7691
Epoch 8/20
937/937 [==============================] - 1s 1ms/step - loss: 0.4657 - accuracy: 0.7747
Epoch 9/20
937/937 [==============================] - 1s 1ms/step - loss: 0.4596 - accuracy: 0.7754
Epoch 10/20
937/937 [==============================] - 1s 1ms/step - loss: 0.4578 - accuracy: 0.7739

In [ ]:
from sklearn.metrics import *
wrong = 0 
pred = []
for i in range(len(test_label)):
    x=round(model.predict(test_data[i].reshape(1, -1))[0][0])
    pred.append((le.inverse_transform([int(x)]))[0])
    if pred[i]!=test_label[i] :
        wrong+=1
print(wrong)
print(accuracy_score(test_label, pred))
print(precision_score(test_label, pred,labels=['h','g'],pos_label='h'))
print(recall_score(test_label, pred,labels=['h','g'],pos_label='h'))
print(f1_score(test_label, pred,average=None))
print(confusion_matrix(test_label, pred))

952
0.7627709942686269
0.6177924217462932
0.8146270818247646
[0.8026534  0.70268582]
[[1936  696]
 [ 256 1125]]
